### PR TITLE
FriendshipsV1: Write tests for basic friendship functionality

### PR DESCRIPTION
**Pull request by angel-mora**
I still don't understand why to set double reationship for friends. Requesting some help from TSEs to solve this issues and continue moving forward

### CODE REVIEW

**Comment by angel-mora** [comment]
Struggling a bit with motivation but looking forward to overcome rabbit-holes

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
# Hello, @angel-mora! :rocket:

As far as I understood you are wondering why to build mutual or reciprocal relationships on that project.

- The kind of relationship defined in that project requirements is a mutual friendship style. It means that it should behave like Facebook or a Linkedin connection. Where both sides of the friendship have the same features available. For example: If you send me an invitation for a friendship on Facebook and I accept that. I can see your posts on my timeline and you can see my posts in your timeline too. No matter who sends the invitation first, we both benefit from the friendship in the same way.

:x: It is different from the model of 'Follow" used on Instagram or Twitter. Where I can follow you and see your posts on my timeline, but it doesn't necessarily mean that you will follow me back.

That article provides a good explanation and a step by step about how to achieve that. Please check it [here](https://smartfunnycool.com/friendships-in-activerecord/).

### Changes Required ♻️ 

- **For now, I can't migrate your database. Please follow the steps provided in the article to set the relationships in the correct way.**
**Hint**: Be aware that because we need to establish a connection with elements of the same table (USER) in different roles, we need to provide some specifications, like the class_name, or a new name for the foreign key.

**I hope I could clarify your questions. Feel free to contact me if something is not clear.** 😃 

### Remember that you were chosen between hundreds of applicants in Microverse and you came this far. We're sure that you have the required to overcome any rabbit-holes. 🥇 💯 

If you feel like you need extra support, please check this article about how to get extra support from full-time TSEs: [here](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-)

Happy Coding!!! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Comment by angel-mora** [comment]
# Set model relations

- Set model relations for friendship
- Write test structures

## Doubts

- Should I use tests as described in Rails Guides or inheriting from Rspec?

**Review by jubaan — CHANGES_REQUESTED** [review]
[![Microverse][microverse-shield]][microverse-url]
<div>
<h1 align="center"> ⚠️ 🛠️ ⚠️ 🛠️ Changes Required 🛠️ ⚠️ 🛠️ ⚠️ </h1>
<br />
<p><b>"Fail fast, fail often"</b> and don't let this discourage you, because <b>only by failing do we learn to succeed</b>.</p>
<details open="open">
  <summary>Review Summary</summary>
  <ol>
    <li><a href="#congrats"> 💯 Awesome work 👏🏼 👏🏼 </a></li>
    <li><a href="#mandatory"> ⚠️ Things to Improve </a> 🚨 🚨 </li>
    <li><a href="#optional"> 💡Nice to have and other comments ✍🏼 ✍🏼 </a></li>
    <li><a href="#contact"> 🧔🏼 About your Reviewer </a> (you don't know it... but we are just automated bots 🤖) </li>
    <li><a href="#acknowledgements"> 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼 </a></li>
  </ol>
</details>
</div>

<h3 id="congrats"> 1. :100: Awesome work</h3>
<details close="close">
<summary> [click to open] Big or little achievements, but achievements at the end. <b>Feel proud that you're learning and improving everyday.</b></summary>


- [ ] Is great that you have chosen a descriptive and meaningful name for the feature branch.
- [ ] Sign-up, log in, and logout are working as expected.


</details>

<hr>
<h3 id="mandatory"> 2. ⚠️ Things to Improve (or the To-Do list to get the project approved) </h3> 
<details close="close">
<summary> [click to open] Working on these observations will help you advance and get closer to the goal 🎯, postpone them or do them half-ways and they'll haunt you 👻 👻... FOREVER!! (It will feel like that, trust me). </summary>


- [ ] PR message is used to summarize the most important changes and mention the features the project has. Please edit the message to match something related to the project.- - [ ] Branch names should be related to the feature or the project.
- [ ] The goal of this project is to let registered users invite, and accept or decline invitations. There should be a way in the views, backed with the logic, to let current users, send requests, accept or reject requests from other users.
- [ ] This button or buttons, should be available at all user sections and on each user profile page.
- [ ] Post timeline should show current login user and his friend's posts.



</details>
<p><b>NOTE</b>This list is or could be divided in what is show in this comment and inline comments posted below.<p>
<hr>

<h3 id="optional"> 3. 💡 Nice to have and other comments </h3>
<details close="close">
<summary> [click to open] </h3></summary>


- I'm reading you're struggling with motivation, this is something that happens to everyone. It's ok if you let your mind jump between focus mode and disperse mode. My recommendation is that you try to prioritize your advance in the program and to think about why you join, think about the big picture and your overall goal and use that as fuel for your motivation. Also, remember that you're not alone, and if you're struggling with something please read the **help** section at the end of this review. There are plenty of channels to ask for help (or a push) 😄.


</details>

<h3 id="contact"> 4. 🧔🏼 About your Reviewer </h3>
<details close="close">
<summary> [click to open] Say "hello world!" on Slack: @jubaan</summary>
<br />
<div align="center">
  <a src="https://www.github.com/jubaan">
    Julio Añoveros
  </a>
  <p>
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    🤖 Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
</div>
</details>

<h3 id="contact"> 5. 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼</h3>
<details close="close">
  <summary> [click to open] <b>Feel stuck?</b> </summary>
  <br>
  <p> First breath... just do it. Take 15-20 min away from the computer, stretch, meditate, do some exercise, drink water, or do whatever is necessary to distract your mind from the obstacle.</p>
  <p><b>Sometimes you just need to get away to see things with a new perspective.</b></p>
</details>

<details close="close">
  <summary> [click to open] <b>Need help?</b> </summary>
  <br>
  <p> Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.</p>
  <p>Remember that <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> has other channels where you can get an answer to your questions:</p>
  <ol>
    <li>The <b>students channel 🧑‍🎓 </b> in slack,</li>
    <li>your <b>teammates 👥 </b>,</li>
    <li>your <b>mentor 👨🏼 👩🏼 </b>, and</li>
    <li><b>Student Success 🏫 </b>.</li>
  </ol>
  <p><b> DON'T hesitate to ask! </b></p>
</details>
<p>If all of the above doesn't help... get a <a href="https://rubberduckdebugging.com/">rubber duck</a> ... it would be great to own one 😄. </p>

<h2 align="center"> Keep up the great work :muscle: and Happy Coding :smiley: :computer:!! </h1>

[microverse-shield]: https://img.shields.io/badge/-microverse-%236F23FF?style=for-the-badge
[microverse-url]: https://www.microverse.org/?grsf=kfm2ej
[bootstrap-shield]: https://img.shields.io/badge/Bootstrap-white?style=for-the-badge&logo=bootstrap
[bootstrap-url]: https://www.microverse.org/?grsf=kfm2ej

**Comment by angel-mora** [comment]
# Changes addressed

- [ ] Test if invitation works
  - [ ] Create two users with ```rails c```
  - [ ] Test invitations between them (review table to check on duplicates  
- [ ] Enable views to friendship_request button
  - [ ] Include pending request transitional button state
- [ ] Create friendships feature test
- [ ] Create friendships views test

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job working on this project so far. However, there are still a few more changes to make in order to get this milestone approved 👍😊🙏

- [x] Please write a descriptive PR summary regarding your made changes on the very same PR. If you have questions or want to leave a note for the reviewers, please leave them as comments.
- [ ] Please follow the Git Flow Guidelines and make the PR requesting to merge the changes to the development branch and not the master.
- [ ] Please attach the ERD as png, not pdf inside the docs directory.
- [ ] The posts timeline should only show the posts of the current logged_in user and his/her |(already accepted friendships) friends
friends_timeline

- [ ] On the all users' page, there should be an "Invite" button under each user who is not a friend with you (the current logged_in user)
user_can_see_invite_buttton

- [ ] User can invite friends
send_invitation

- [ ] User can accept or reject a friendship request
accept_reject_friendship

- [x] You have to write unit and integration tests for your models and for the features of the application.
tests


<hr>

Kindly do the above-required changes in order to move on to the next milestone 😊
You can always reach me on Slack with the name "Mahmoud Bakr"
Regarding your question on the PR summary, In this milestone, you have to set up your models and views in a way that satisfies the above changes

<hr>

Good luck and happy coding 👨‍💻💻

**Comment by angel-mora** [comment]
# WEEK UPDATES

I got into an Improvement Period for opportunity areas regarding my productivity. As currently working alone, decided to request PR to advance only in tests to feel I'm moving forward. 

## Things done March 1-5 week

- [x] Test if invitation works
- [x] Create friendships feature test
- [x] Create friendships views test

## Pending TODOs to complete this weekend

- [ ] Test invitations to check on duplicates  
- [ ] Enable views to friendship_request button html.erb
- [ ] Implement pending request transitional button state

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @angel-mora, good job on adding the tests, however, I noticed you're yet to implement most of the requested changes, I will go ahead and add them below, kindly implement all changes before requesting another code review.

* [x] User should be able to invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User should be able to see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] There is a button to invite user to friendship on users list page and on single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] You tests files must have a suffix of `_spec` else RSpec will not recognize it. Running `rspec` shows zero example even when you have tests files. Kindly update accordingly
* [x] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. The affected file is inside `app/views/layouts/application.html.erb`  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by angel-mora** [comment]
ALL CHANGES ADDRESSED!

Project completed.

- All changes from last TSE addressed
- Users can only see posts from their friends, can send, accept and decline invitations

**Comment by rukundoeric** [comment]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professinal. 💯 

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
